from __future__ import annotations

from typing import Protocol

from app.agents.schemas import AgentInvocation
from app.models.event import TaskEvent
from app.models.memory import CandidateMemory
from app.models.plan import ExecutionPlan
from app.models.task import Task
from app.tools.base import ToolInvocationResult


class Storage(Protocol):
    def init_db(self) -> None: ...
    def create_task(self, task: Task) -> None: ...
    def get_task(self, task_id: str) -> Task | None: ...
    def update_task(self, task: Task) -> None: ...
    def append_event(self, event: TaskEvent) -> None: ...
    def get_events(self, task_id: str) -> list[TaskEvent]: ...
    def save_plan(self, plan: ExecutionPlan) -> None: ...
    def get_plan(self, task_id: str) -> ExecutionPlan | None: ...
    def save_memory(self, memory: CandidateMemory) -> None: ...
    def get_memories(self) -> list[CandidateMemory]: ...
    def get_memory(self, memory_id: str) -> CandidateMemory | None: ...
    def update_memory(self, memory: CandidateMemory) -> None: ...
    def save_tool_invocation(self, invocation: ToolInvocationResult) -> None: ...
    def save_agent_invocation(self, invocation: AgentInvocation) -> None: ...
